# Generated by Django 4.0.4 on 2022-04-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
